nutritious-foods:
 file-path: plugins/NutritiousFoods/data.yml
 effect-tick-period: 600
 
 #maximum value of this is about 80
 max-nutrient-level: 80
 start-nutrient-level: 60
 nutrient-levels-per-hour: 6.0
 nutrient-levels-per-hour-slow: 2.0

 hunger-level-decrease-chance: 0.333

 nutrients:
  Carbs:
   effects:
    SLOW_DIGGING:
     level-minimum: 1
     level-variance: 2
     duration-minimum: 0.25
     duration-variance: 0.75

    CONFUSION:
     level-minimum: 1
     level-variance: 0
     duration-minimum: 0.05
     duration-variance: 0.95

  Vitamins:
   effects:
    SLOW:
     level-minimum: 1
     level-variance: 2
     duration-minimum: 0.25
     duration-variance: 0.75

    BLINDNESS:
     level-minimum: 1
     level-variance: 0
     duration-minimumn: 0.05
     duration-variance: 0.95

  Protein:
   effects:
    WEAKNESS:
     level-minimum: 1
     level-variance: 2
     duration-minimum: 0.10
     duration-variance: 0.90

    HUNGER:
     level-minimum: 1
     level-variance: 1
     duration-minimum: 0.5
     duration-variance: 0.5
 
 foods:
  BREAD:
   hunger: 4
   saturation: 1.0
   Carbs: 9

  CARROT_ITEM:
   hunger: 1
   saturation: 0.5
   Vitamins: 2
   Protein: 1

  POTATO_ITEM:
   hunger: 1
   saturation: 3.0
   Carbs: 1
   Vitamins: 1
   Protein: 1

  RAW_FISH:
   hunger: 0
   saturation: 0.0
   Protein: 1

  COOKED_FISH:
   hunger: 1
   saturation: 1.0
   Protein: 1

  PORK:
   hunger: 0
   saturation: 0.0
   Vitamins: 2
   Protein: 3

  GRILLED_PORK:
   hunger: 2
   saturation: 1.0
   Vitamins: 2
   Protein: 3

  RAW_BEEF:
   hunger: 0
   saturation: 0
   Protein: 4

  COOKED_BEEF:
   hunger: 2
   saturation: 5.0
   Protein: 4

  MILK_BUCKET:
   hunger: 1
   saturation: 2.0
   Vitamins: 2

  ROTTEN_FLESH:
   hunger: 1.0
   saturation: -1.0
   Vitamins: -3
  
  SPIDER_EYE:
   hunger: 1.0
   saturation: -1.0
   Carbs: -3

  APPLE:
   hunger: 1
   saturation: 2.0

  GOLDEN_APPLE:
   hunger: 0
   saturation: 2.0

  PUMPKIN_PIE:
   hunger: 3
   saturation: 3.0

  MELON:
   hunger: 1
   saturation: 0.0

  CAKE:
   hunger: 3
   saturation: 6.0

  COOKIE:
   hunger: 1
   saturation: 0.0

  RAW_CHICKEN:
   hunger: 0
   saturation: 0.0

  COOKED_CHICKEN:
   hunger: 1
   saturation: 1.0
  
  MUSHROOM_SOUP:
   hunger: 3.0
   saturation: 2.0
