exists: true
effectTickPeriod: 60.0
expectedPlayerCap: 10

nutrients:
 -name: Vitamin-A
  maxLevel: 128
  rateAtMaxLevel: 1.0
  medLevel: 96
  rateAtMaxLevel: 0.2
  foods: [[Carrot, 4],[GoldenCarrot,16]]
  effects:
   -type: slowdigging
    cutoff: 64
    moreThan: false
    periodMax: 10
    intensityMax: 4
    durationMax: 30.0

 -name: Vitamin-B
  maxLevel: 128
  rateAtMaxLevel: 1.0
  medLevel: 96
  rateAtMaxLevel: 0.2
  foods: [[Bread, 4],[GoldenCarrot,16]]
  effects:
   -type: poison
    cutoff: 64
    moreThan: false
    periodMax: 10
    intensityMax: 4
    durationMax: 30.0

 -name: Vitamin-C
  maxLevel: 128
  rateAtMaxLevel: 1.0
  medLevel: 96
  rateAtMaxLevel: 0.2
  foods: [[Carrot, 4],[GoldenCarrot,16]]
  effects:
   -type: blindness
    cutoff: 64
    moreThan: false
    periodMax: 10
    intensityMax: 4
    durationMax: 30.0