name: NutritiousFoods
main: com.github.jacobcole2000.NutritiousFoods.NutritiousFoods
version: 0.0.1

commands:
   nfcheck:
      description: check player nutrition levels
      usage: /<command> [player]