name: NutritiousFoods
main: com.github.jacobcole2000.NutritiousFoods.NutritiousFoods
version: 0.0.1

commands:
 nfcheck:
  description: check player nutrition levels
  usage: /<command>
 nfc:
  description: check player nutrition levels
  usage: /<command>
 nfinfo:
  description: get information about a specific nutrient
  usage: /<command> [nutrient]
 nfi:
  description: get information about a specific nutrient
  usage: /<command> [nutrient or nutrient index]
 nfverbose:
  description: toggle verbose mode
  usage: /<command>
 nfv:
  description: toggle verbose mode
  usage: /<command>