name: NutritiousFoods
main: com.github.jacobcole2000.NutritiousFoods.NutritiousFoods
version: 0.0.1

commands:
  nfc:
    description: NutritiousFoods Check. Check nutrient levels
    usage: /nfc

  nfi:
    description: NutritiousFoods Info. Check nutrient-level restoration of a food item in hand.
    usage: /nfi

permissions:
  NutritiousFoods.*:
    description: Gives access to all NutrititiousFoods commands
    children:
      NutritiousFoods.uneffected: true
  NutritiousFoods.uneffected:
    description: Character is uneffected by nutrition effects
    default: op