name: NutritiousFoods
main: com.github.jacobcole2000.NutritiousFoods.NutritiousFoods
version: 0.0.1

commands:
  nfc:
    description: NutritiousFoods Check. Check nutrient levels
    usage: /nfc
    permission-message: You don't have <permission>